# Generated by Django 5.2.17 on 2026-09-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showtimes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
